In [2]:
#import basic libraries
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import os

In [3]:
data = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/00471/Data_for_UCI_named.csv")
#data = pd.read_csv("C:\\Users\\Abdulrazaq\\Documents\\py learn\\HAMOYE\\Hamoye stage C\\Data_for_UCI_named.csv")

In [4]:
data

,tau1,tau2,tau3,tau4,p1,p2,p3,p4,g1,g2,g3,g4,stab,stabf
0,2.959060,3.079885,8.381025,9.780754,3.763085,-0.782604,-1.257395,-1.723086,0.650456,0.859578,0.887445,0.958034,0.055347,unstable
1,9.304097,4.902524,3.047541,1.369357,5.067812,-1.940058,-1.872742,-1.255012,0.413441,0.862414,0.562139,0.781760,-0.005957,stable
2,8.971707,8.848428,3.046479,1.214518,3.405158,-1.207456,-1.277210,-0.920492,0.163041,0.766689,0.839444,0.109853,0.003471,unstable
3,0.716415,7.669600,4.486641,2.340563,3.963791,-1.027473,-1.938944,-0.997374,0.446209,0.976744,0.929381,0.362718,0.028871,unstable
4,3.134112,7.608772,4.943759,9.857573,3.525811,-1.125531,-1.845975,-0.554305,0.797110,0.455450,0.656947,0.820923,0.049860,unstable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2.930406,9.487627,2.376523,6.187797,3.343416,-0.658054,-1.449106,-1.236256,0.601709,0.779642,0.813512,0.608385,0.023892,unstable
9996,3.392299,1.274827,2.954947,6.894759,4.349512,-1.663661,-0.952437,-1.733414,0.502079,0.567242,0.285880,0.366120,-0.025803,stable
9997,2.364034,2.842030,8.776391,1.008906,4.299976,-1.380719,-0.943884,-1.975373,0.487838,0.986505,0.149286,0.145984,-0.031810,stable
9998,9.631511,3.994398,2.757071,7.821347,2.514755,-0.966330,-0.649915,-0.898510,0.365246,0.587558,0.889118,0.818391,0.037789,unstable
9999,6.530527,6.781790,4.349695,8.673138,3.492807,-1.390285,-1.532193,-0.570329,0.073056,0.505441,0.378761,0.942631,0.045263,unstable

In [5]:
X = data.drop(columns =["stabf"])
y = pd.DataFrame()
y["stabf"] = data["stabf"]
y

         stabf
0     unstable
1       stable
2     unstable
3     unstable
4     unstable
...        ...
9995  unstable
9996    stable
9997    stable
9998  unstable
9999  unstable

[10000 rows x 1 columns]

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,y, test_size = 0.3,
                                                 random_state = 42)

In [11]:
X_train.shape,X_test.shape, y_train.shape,y_test.shape

((7000, 13), (3000, 13), (7000, 1), (3000, 1))

In [9]:
#Question 14:accuracy of testset with random forest
from sklearn.ensemble import RandomForestClassifier
rand = RandomForestClassifier().fit(X_train,y_train)
rand_pred =rand.predict(X_test)

C:\Users\Abdulrazaq\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

In [10]:
from sklearn.metrics import accuracy_score
acc =(accuracy_score(rand_pred,y_test))
round(acc,4)

0.9997

In [12]:
#Question 15
import xgboost
from xgboost import XGBClassifier
xg = XGBClassifier().fit(X_train,y_train)
xg_pre=xg.predict(X_test)
acc_xg =(accuracy_score(xg_pre,y_test))
round(acc_xg,4)

C:\Users\Abdulrazaq\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\Abdulrazaq\Anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

0.9997

In [32]:
#question 16
from sklearn.ensemble import ExtraTreesClassifier
extra= ExtraTreesClassifier()

param_grid = [{'n_estimators': [50, 100, 300, 500, 1000],
 " min_samples_split" :[2, 3, 5, 7, 9],
  "min_samples_leaf" : [1, 2, 4, 6, 8],'max_features': ['auto', 'sqrt', 'log2', None]},
 {'bootstrap': [False]}]

In [39]:
param_distributions = param_grid
from sklearn.model_selection import RandomizedSearchCV
rando = RandomizedSearchCV(extra,
                           param_distributions,
                           cv=5,n_iter=10, scoring = 'accuracy', n_jobs = -1, verbose = 1,random_state = 1)